/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peliculas;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author jortega
 */
public class VentanaAplicarModificacion extends javax.swing.JFrame {

    String[] pelicula;
    
    private void aplicarCambios(String archivo) {
    File archivoFile = new File(archivo);
    StringBuilder contenidoActualizado = new StringBuilder();

    try (BufferedReader reader = new BufferedReader(new FileReader(archivoFile))) {
        String linea;

        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split("\t");

            if (datos[0].trim().equals(pelicula[0].trim())) {
                contenidoActualizado.append(nuevoTituloField.getText().trim()).append("\t")
                        .append(nuevoEstrenoField.getText().trim()).append("\t")
                        .append(nuevoDirectorField.getText().trim()).append("\n");
            } else {
                contenidoActualizado.append(linea).append("\n");
            }
        }
    } catch (IOException e) {
        System.err.println("Error leyendo el archivo: " + e.getMessage());
        return;
    }

    try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivoFile))) {
        writer.write(contenidoActualizado.toString());
    } catch (IOException e) {
        System.err.println("Error escribiendo el archivo: " + e.getMessage());
    }
}


    
    public void obtenerPelicula(String[] peliculaModificar){
        pelicula = peliculaModificar;
        if (pelicula != null && pelicula.length >= 3) {
            nuevoTituloField.setText(pelicula[0]);
            nuevoEstrenoField.setText(pelicula[1]);
            nuevoDirectorField.setText(pelicula[2]);
        } else {
            System.err.println("Los datos de la película son inválidos.");
        }
    }
    
    /**
     * Creates new form VentanaAplicarModificacion
     */
    public VentanaAplicarModificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emptyDialog = new javax.swing.JDialog();
        emptyPanel = new javax.swing.JOptionPane();
        aplicarModificacionDesktopPanel = new javax.swing.JDesktopPane();
        aplicarModificacionFrame = new javax.swing.JInternalFrame();
        nuevoTituloLabel = new javax.swing.JLabel();
        nuevoTituloField = new javax.swing.JTextField();
        nuevoEstrenoLabel = new javax.swing.JLabel();
        nuevoEstrenoField = new javax.swing.JTextField();
        nuevoDirectorLabel = new javax.swing.JLabel();
        nuevoDirectorField = new javax.swing.JTextField();
        aplicarButton = new javax.swing.JButton();

        emptyDialog.setSize(new java.awt.Dimension(300, 200));

        emptyPanel.setMessageType(JOptionPane.WARNING_MESSAGE);

        javax.swing.GroupLayout emptyDialogLayout = new javax.swing.GroupLayout(emptyDialog.getContentPane());
        emptyDialog.getContentPane().setLayout(emptyDialogLayout);
        emptyDialogLayout.setHorizontalGroup(
            emptyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        emptyDialogLayout.setVerticalGroup(
            emptyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        aplicarModificacionFrame.setVisible(true);

        nuevoTituloLabel.setText("Nuevo título:");

        nuevoEstrenoLabel.setText("Nuevo año de estreno:");

        nuevoDirectorLabel.setText("Nuevo director:");

        aplicarButton.setText("Aplicar");
        aplicarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aplicarModificacionFrameLayout = new javax.swing.GroupLayout(aplicarModificacionFrame.getContentPane());
        aplicarModificacionFrame.getContentPane().setLayout(aplicarModificacionFrameLayout);
        aplicarModificacionFrameLayout.setHorizontalGroup(
            aplicarModificacionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aplicarModificacionFrameLayout.createSequentialGroup()
                .addGroup(aplicarModificacionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aplicarModificacionFrameLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(aplicarModificacionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nuevoDirectorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuevoEstrenoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuevoTituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(aplicarModificacionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nuevoTituloField)
                            .addComponent(nuevoEstrenoField)
                            .addComponent(nuevoDirectorField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(aplicarModificacionFrameLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(aplicarButton)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        aplicarModificacionFrameLayout.setVerticalGroup(
            aplicarModificacionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aplicarModificacionFrameLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(aplicarModificacionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoTituloLabel)
                    .addComponent(nuevoTituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aplicarModificacionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoEstrenoLabel)
                    .addComponent(nuevoEstrenoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aplicarModificacionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoDirectorLabel)
                    .addComponent(nuevoDirectorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(aplicarButton)
                .addGap(43, 43, 43))
        );

        aplicarModificacionDesktopPanel.setLayer(aplicarModificacionFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout aplicarModificacionDesktopPanelLayout = new javax.swing.GroupLayout(aplicarModificacionDesktopPanel);
        aplicarModificacionDesktopPanel.setLayout(aplicarModificacionDesktopPanelLayout);
        aplicarModificacionDesktopPanelLayout.setHorizontalGroup(
            aplicarModificacionDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aplicarModificacionDesktopPanelLayout.createSequentialGroup()
                .addComponent(aplicarModificacionFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        aplicarModificacionDesktopPanelLayout.setVerticalGroup(
            aplicarModificacionDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aplicarModificacionFrame)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aplicarModificacionDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aplicarModificacionDesktopPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarButtonActionPerformed
        emptyPanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (emptyDialog.isVisible() && e.getSource() == emptyPanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                emptyDialog.setVisible(false);
                emptyDialog.dispose();
                emptyPanel.setValue(null);
            }
        });
        
        if(nuevoTituloField.getText().isEmpty() || nuevoEstrenoField.getText().isEmpty() || nuevoDirectorField.getText().isEmpty()){
            emptyDialog.setLocationRelativeTo(this);
            emptyDialog.setVisible(true);
        } else{
            aplicarCambios("datos.tsv");
            dispose();
        }
    }//GEN-LAST:event_aplicarButtonActionPerformed

    public void setEmptyDialog(String mensaje, String boton, String titulo){
        emptyPanel.setMessage(mensaje);
        emptyPanel.setOptions(new Object[]{boton});
        emptyDialog.setTitle(titulo);
    }
    
    public void setTituloVentana(String titulo){
        aplicarModificacionFrame.setTitle(titulo);
    }
    
    public void setLabels(String titulo, String año, String director){
        nuevoTituloLabel.setText(titulo);
        nuevoEstrenoLabel.setText(año);
        nuevoDirectorLabel.setText(director);
    }
    
    public void setAplicarButton(String texto){
        aplicarButton.setText(texto);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarButton;
    private javax.swing.JDesktopPane aplicarModificacionDesktopPanel;
    private javax.swing.JInternalFrame aplicarModificacionFrame;
    private javax.swing.JDialog emptyDialog;
    private javax.swing.JOptionPane emptyPanel;
    private javax.swing.JTextField nuevoDirectorField;
    private javax.swing.JLabel nuevoDirectorLabel;
    private javax.swing.JTextField nuevoEstrenoField;
    private javax.swing.JLabel nuevoEstrenoLabel;
    private javax.swing.JTextField nuevoTituloField;
    private javax.swing.JLabel nuevoTituloLabel;
    // End of variables declaration//GEN-END:variables
}
