/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peliculas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author jortega
 */
public class VentanaModificar extends javax.swing.JFrame {

    private final VentanaAplicarModificacion ventanaAplicarModificacion = new VentanaAplicarModificacion();
    
    private void modificarDatos(String archivo) {
    File archivoFile = new File(archivo);
    boolean existe = false;
    String[] peliculaModificar = null;

    try (BufferedReader reader = new BufferedReader(new FileReader(archivoFile))) {
        String linea;
        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split("\t");
            if (datos[0].trim().equals(tituloField.getText().trim())) {
                existe = true;
                peliculaModificar = linea.split("\t");
                break; 
            }
        }
    } catch (IOException e) {
        System.err.println("Error leyendo el archivo: " + e.getMessage());
    }

    if (existe) {
        tituloField.setText("");
        ventanaAplicarModificacion.obtenerPelicula(peliculaModificar);
        ventanaAplicarModificacion.setLocationRelativeTo(this);
        ventanaAplicarModificacion.setVisible(true);
    } else {
        tituloField.setText("");
        noExisteDialog.setLocationRelativeTo(this);
        noExisteDialog.setVisible(true);
    }
}

    
    
    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noExisteDialog = new javax.swing.JDialog();
        noExistePanel = new javax.swing.JOptionPane();
        emptyDialog = new javax.swing.JDialog();
        emptyPanel = new javax.swing.JOptionPane();
        modificarDesktopPanel = new javax.swing.JDesktopPane();
        modificarFrame = new javax.swing.JInternalFrame();
        tituloField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        buscarLabel = new javax.swing.JLabel();

        noExisteDialog.setSize(new java.awt.Dimension(300, 200));

        noExistePanel.setMessageType(JOptionPane.ERROR_MESSAGE);

        javax.swing.GroupLayout noExisteDialogLayout = new javax.swing.GroupLayout(noExisteDialog.getContentPane());
        noExisteDialog.getContentPane().setLayout(noExisteDialogLayout);
        noExisteDialogLayout.setHorizontalGroup(
            noExisteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noExistePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        noExisteDialogLayout.setVerticalGroup(
            noExisteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noExistePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        emptyDialog.setSize(new java.awt.Dimension(300, 200));

        emptyPanel.setMessageType(JOptionPane.WARNING_MESSAGE);

        javax.swing.GroupLayout emptyDialogLayout = new javax.swing.GroupLayout(emptyDialog.getContentPane());
        emptyDialog.getContentPane().setLayout(emptyDialogLayout);
        emptyDialogLayout.setHorizontalGroup(
            emptyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        emptyDialogLayout.setVerticalGroup(
            emptyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modificarFrame.setClosable(true);
        modificarFrame.setVisible(true);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        buscarLabel.setText("Busca la película que quieras modificar");
        buscarLabel.setToolTipText("");

        javax.swing.GroupLayout modificarFrameLayout = new javax.swing.GroupLayout(modificarFrame.getContentPane());
        modificarFrame.getContentPane().setLayout(modificarFrameLayout);
        modificarFrameLayout.setHorizontalGroup(
            modificarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarFrameLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(modificarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(tituloField))
                .addGap(18, 18, 18)
                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        modificarFrameLayout.setVerticalGroup(
            modificarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(buscarLabel)
                .addGap(18, 18, 18)
                .addGroup(modificarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        modificarDesktopPanel.setLayer(modificarFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout modificarDesktopPanelLayout = new javax.swing.GroupLayout(modificarDesktopPanel);
        modificarDesktopPanel.setLayout(modificarDesktopPanelLayout);
        modificarDesktopPanelLayout.setHorizontalGroup(
            modificarDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificarFrame, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        modificarDesktopPanelLayout.setVerticalGroup(
            modificarDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificarDesktopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificarDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        emptyPanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (emptyDialog.isVisible() && e.getSource() == emptyPanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                emptyDialog.setVisible(false);
                emptyDialog.dispose();
                emptyPanel.setValue(null);
            }
        });
        
        noExistePanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (noExisteDialog.isVisible() && e.getSource() == noExistePanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                noExisteDialog.setVisible(false);
                noExisteDialog.dispose();
                noExistePanel.setValue(null);
            }
        });
        
        if(tituloField.getText().isEmpty()){
            emptyDialog.setLocationRelativeTo(this);
            emptyDialog.setVisible(true);
        } else{
            modificarDatos("datos.tsv");
        }
        
        
    }//GEN-LAST:event_buscarButtonActionPerformed

    public void setTituloVentana(String titulo){
        modificarFrame.setTitle(titulo);
        ventanaAplicarModificacion.setTituloVentana(titulo);
    }
    
    public void setBuscarLabel(String texto){
        buscarLabel.setText(texto);
    }
    
    public void setBuscarButton(String boton){
        buscarButton.setText(boton);
    }
    
    public void setEmptyDialog(String mensaje, String boton, String titulo){
        emptyPanel.setMessage(mensaje);
        emptyPanel.setOptions(new Object[]{boton});
        emptyDialog.setTitle(titulo);
    }
    
    public void setNoExisteDialog(String mensaje, String boton, String titulo){
        noExistePanel.setMessage(mensaje);
        noExistePanel.setOptions(new Object[]{boton});
        noExisteDialog.setTitle(titulo);
    }
    
    public void setAplicarLabels(String titulo, String año, String director){
        ventanaAplicarModificacion.setLabels(titulo, año, director);
    }
    
    public void setAplicarButton(String texto){
        ventanaAplicarModificacion.setAplicarButton(texto);
    }
    
    public void setAplicarEmptyDialog(String mensaje, String boton, String titulo){
        ventanaAplicarModificacion.setEmptyDialog(mensaje, boton, titulo);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel buscarLabel;
    private javax.swing.JDialog emptyDialog;
    private javax.swing.JOptionPane emptyPanel;
    private javax.swing.JDesktopPane modificarDesktopPanel;
    private javax.swing.JInternalFrame modificarFrame;
    private javax.swing.JDialog noExisteDialog;
    private javax.swing.JOptionPane noExistePanel;
    private javax.swing.JTextField tituloField;
    // End of variables declaration//GEN-END:variables
}
