/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peliculas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author jortega
 */
public class VentanaConsultar extends javax.swing.JFrame {
    
    public void consultarElementosArchivo(String archivo, String titulo, String añoEstreno, String director) {
        File archivoFile = new File(archivo);

        try (BufferedReader reader = new BufferedReader(new FileReader(archivoFile))) {
            StringBuilder lineas = new StringBuilder("<html>");

            reader.lines().forEach(linea -> {
                String[] partes = linea.split("\t");
                lineas.append("<u>").append(titulo).append("</u>: ").append(partes[0])
                      .append(" - <u>").append(añoEstreno).append("</u>: ").append(partes[1])
                      .append(" - <u>").append(director).append("</u>: ").append(partes[2]).append("<br>");
            });

            lineas.append("</html>");
            datosLabel.setText(lineas.toString());
        } catch (IOException e) {
            System.err.println("Error leyendo el archivo: " + e.getMessage());
        }
    }




    
    /**
     * Creates new form VentanaConsultar
     */
    public VentanaConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarDesktopPanel = new javax.swing.JDesktopPane();
        consultarFrame = new javax.swing.JInternalFrame();
        datosLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        consultarFrame.setClosable(true);
        consultarFrame.setVisible(true);

        javax.swing.GroupLayout consultarFrameLayout = new javax.swing.GroupLayout(consultarFrame.getContentPane());
        consultarFrame.getContentPane().setLayout(consultarFrameLayout);
        consultarFrameLayout.setHorizontalGroup(
            consultarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        consultarFrameLayout.setVerticalGroup(
            consultarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        consultarDesktopPanel.setLayer(consultarFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout consultarDesktopPanelLayout = new javax.swing.GroupLayout(consultarDesktopPanel);
        consultarDesktopPanel.setLayout(consultarDesktopPanelLayout);
        consultarDesktopPanelLayout.setHorizontalGroup(
            consultarDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarDesktopPanelLayout.createSequentialGroup()
                .addComponent(consultarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        consultarDesktopPanelLayout.setVerticalGroup(
            consultarDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarDesktopPanelLayout.createSequentialGroup()
                .addComponent(consultarFrame)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(consultarDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(consultarDesktopPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTituloVentana(String titulo){
        consultarFrame.setTitle(titulo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane consultarDesktopPanel;
    private javax.swing.JInternalFrame consultarFrame;
    private javax.swing.JLabel datosLabel;
    // End of variables declaration//GEN-END:variables
}
