/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peliculas;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;
/**
 *
 * @author jortega
 */
public class VentanaAñadir extends javax.swing.JFrame {

    
    /**
     * Creates new form VentanaAñadir
     */
    public VentanaAñadir() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primaryKeyDialog = new javax.swing.JDialog();
        primaryKeyPanel = new javax.swing.JOptionPane();
        emptyDialog = new javax.swing.JDialog();
        emptyPanel = new javax.swing.JOptionPane();
        informationDialog = new javax.swing.JDialog();
        informationPanel = new javax.swing.JOptionPane();
        añadirDesktopPanel = new javax.swing.JDesktopPane();
        añadirFrame = new javax.swing.JInternalFrame();
        tituloLabel = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        añoLabel = new javax.swing.JLabel();
        estrenoField = new javax.swing.JTextField();
        directorLabel = new javax.swing.JLabel();
        directorField = new javax.swing.JTextField();
        añadirButton = new javax.swing.JButton();

        primaryKeyDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        primaryKeyDialog.setMaximumSize(new java.awt.Dimension(1000, 2000));
        primaryKeyDialog.setMinimumSize(new java.awt.Dimension(30, 20));
        primaryKeyDialog.setSize(new java.awt.Dimension(350, 200));

        primaryKeyPanel.setMessageType(JOptionPane.ERROR_MESSAGE);
        primaryKeyPanel.setMaximumSize(new java.awt.Dimension(300, 200));
        primaryKeyPanel.setMinimumSize(new java.awt.Dimension(300, 150));
        primaryKeyPanel.setPreferredSize(new java.awt.Dimension(300, 150));

        javax.swing.GroupLayout primaryKeyDialogLayout = new javax.swing.GroupLayout(primaryKeyDialog.getContentPane());
        primaryKeyDialog.getContentPane().setLayout(primaryKeyDialogLayout);
        primaryKeyDialogLayout.setHorizontalGroup(
            primaryKeyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, primaryKeyDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(primaryKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        primaryKeyDialogLayout.setVerticalGroup(
            primaryKeyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryKeyDialogLayout.createSequentialGroup()
                .addComponent(primaryKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        emptyDialog.setSize(new java.awt.Dimension(300, 200));

        emptyPanel.setMessageType(JOptionPane.WARNING_MESSAGE);

        javax.swing.GroupLayout emptyDialogLayout = new javax.swing.GroupLayout(emptyDialog.getContentPane());
        emptyDialog.getContentPane().setLayout(emptyDialogLayout);
        emptyDialogLayout.setHorizontalGroup(
            emptyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        emptyDialogLayout.setVerticalGroup(
            emptyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        informationDialog.setSize(new java.awt.Dimension(300, 200));

        informationPanel.setMessageType(JOptionPane.INFORMATION_MESSAGE);

        javax.swing.GroupLayout informationDialogLayout = new javax.swing.GroupLayout(informationDialog.getContentPane());
        informationDialog.getContentPane().setLayout(informationDialogLayout);
        informationDialogLayout.setHorizontalGroup(
            informationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        informationDialogLayout.setVerticalGroup(
            informationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        añadirFrame.setClosable(true);
        añadirFrame.setVisible(true);

        tituloLabel.setText("Titulo de la película:");

        añoLabel.setText("Año de estreno:");

        directorLabel.setText("Director:");

        añadirButton.setText("Añadir película");
        añadirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        añadirButton.setMaximumSize(new java.awt.Dimension(160, 24));
        añadirButton.setMinimumSize(new java.awt.Dimension(160, 24));
        añadirButton.setPreferredSize(new java.awt.Dimension(160, 24));
        añadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout añadirFrameLayout = new javax.swing.GroupLayout(añadirFrame.getContentPane());
        añadirFrame.getContentPane().setLayout(añadirFrameLayout);
        añadirFrameLayout.setHorizontalGroup(
            añadirFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirFrameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(añadirFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tituloField)
                    .addComponent(tituloLabel)
                    .addComponent(añoLabel)
                    .addComponent(estrenoField)
                    .addComponent(directorField, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(directorLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirFrameLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(añadirButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        añadirFrameLayout.setVerticalGroup(
            añadirFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirFrameLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(añoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estrenoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(directorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(añadirButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        añadirDesktopPanel.setLayer(añadirFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout añadirDesktopPanelLayout = new javax.swing.GroupLayout(añadirDesktopPanel);
        añadirDesktopPanel.setLayout(añadirDesktopPanelLayout);
        añadirDesktopPanelLayout.setHorizontalGroup(
            añadirDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(añadirFrame)
        );
        añadirDesktopPanelLayout.setVerticalGroup(
            añadirDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(añadirFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(añadirDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(añadirDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirButtonActionPerformed
        emptyPanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (emptyDialog.isVisible() && e.getSource() == emptyPanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                emptyDialog.setVisible(false);
                emptyDialog.dispose();
                emptyPanel.setValue(null);
            }
        });
        
        primaryKeyPanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (primaryKeyDialog.isVisible() && e.getSource() == primaryKeyPanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                primaryKeyDialog.setVisible(false);
                primaryKeyDialog.dispose();
                primaryKeyPanel.setValue(null);
            }
        });
        
        informationPanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (informationDialog.isVisible() && e.getSource() == informationPanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                informationDialog.setVisible(false);
                informationDialog.dispose();
                informationPanel.setValue(null);
            }
        });
        
        añadirElementosArchivo("datos.tsv");
        
    }//GEN-LAST:event_añadirButtonActionPerformed

    
    private void añadirElementosArchivo(String archivo) {
    File archivoFile = new File(archivo);
    boolean existe = false;

    try (BufferedReader reader = new BufferedReader(new FileReader(archivoFile))) {
        String linea;
        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split("\t");
            if (datos.length > 0 && datos[0].equalsIgnoreCase(tituloField.getText().trim())) {
                existe = true;
                break;
            }
        }
    } catch (IOException e) {
        System.err.println("Error leyendo el archivo: " + e.getMessage());
    }

    if (existe) {
        primaryKeyDialog.setLocationRelativeTo(this);      
        primaryKeyDialog.setVisible(true);
    } else {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivoFile, true))) {
            if (tituloField.getText().isEmpty() || estrenoField.getText().isEmpty() || directorField.getText().isEmpty()) {
                emptyDialog.setLocationRelativeTo(this);      
                emptyDialog.setVisible(true);
            } else {
                writer.write(tituloField.getText() + "\t" + estrenoField.getText() + "\t" + directorField.getText());
                writer.newLine();
                
                informationDialog.setLocationRelativeTo(this);      
                informationDialog.setVisible(true);
                
                tituloField.setText("");
                estrenoField.setText("");
                directorField.setText("");
            }
        } catch (IOException e) {
            System.err.println("Error escribiendo en el archivo: " + e.getMessage());
        }
    }
}






    public void setTituloVentana(String titulo){
        añadirFrame.setTitle(titulo);
    }
    
    public void setTituloLabel(String titulo){
        tituloLabel.setText(titulo);
    }
    
    public void setAñoLabel(String año){
        añoLabel.setText(año);
    }
    
    public void setDirectorLabel(String director){
        directorLabel.setText(director);
    }
    
    public void setAñadirButton(String texto){
        añadirButton.setText(texto);
    }
    
    public void setprimaryKeyDialog(String mensaje, String Boton, String titulo){
        primaryKeyPanel.setMessage(mensaje);
        primaryKeyPanel.setOptions(new Object[]{Boton});
        primaryKeyDialog.setTitle(titulo);

    }
    
    public void setemptyPanelDialog(String mensaje, String Boton, String titulo){
        emptyPanel.setMessage(mensaje);
        emptyPanel.setOptions(new Object[]{Boton});
        emptyDialog.setTitle(titulo);

    }
    
    public void setInformationPanelDialog(String mensaje, String boton, String titulo){
        informationPanel.setMessage(mensaje);
        informationPanel.setOptions(new Object[]{boton});
        informationDialog.setTitle(titulo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirButton;
    private javax.swing.JDesktopPane añadirDesktopPanel;
    private javax.swing.JInternalFrame añadirFrame;
    private javax.swing.JLabel añoLabel;
    private javax.swing.JTextField directorField;
    private javax.swing.JLabel directorLabel;
    private javax.swing.JDialog emptyDialog;
    private javax.swing.JOptionPane emptyPanel;
    private javax.swing.JTextField estrenoField;
    private javax.swing.JDialog informationDialog;
    private javax.swing.JOptionPane informationPanel;
    private javax.swing.JDialog primaryKeyDialog;
    private javax.swing.JOptionPane primaryKeyPanel;
    private javax.swing.JTextField tituloField;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
