/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peliculas;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jortega
 */
public class VentanaEliminar extends javax.swing.JFrame {

    
    /**
     * Creates new form VentanaEliminar
     */
    public VentanaEliminar() {
        initComponents();
    }
    
    private void eliminarPelicula(String archivo){
    File archivoFile = new File(archivo);
    List<String> lineas = new ArrayList<>();
    boolean existe = false;
    
    try (BufferedReader reader = new BufferedReader(new FileReader(archivoFile))) {
        String linea;
        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split("\t");
            if (!datos[0].trim().equals(tituloField.getText().trim())) {
                lineas.add(linea);
            } else {
                existe = true;
            }
        }
    } catch (IOException e) {
        System.err.println("Error leyendo el archivo: " + e.getMessage());
    }

    try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivoFile))) {
        for (String linea : lineas) {
            writer.write(linea);
            writer.newLine();
        }

        if (existe) {
            tituloField.setText("");
            eliminadaDialog.setLocationRelativeTo(this);
            eliminadaDialog.setVisible(true);
        } else {
            tituloField.setText("");
            noExisteDialog.setLocationRelativeTo(this);
            noExisteDialog.setVisible(true);
        }

    } catch (IOException e) {
        System.err.println("Error escribiendo en el archivo: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminadaDialog = new javax.swing.JDialog();
        eliminadaPanel = new javax.swing.JOptionPane();
        noExisteDialog = new javax.swing.JDialog();
        noExistePanel = new javax.swing.JOptionPane();
        emptyDialog = new javax.swing.JDialog();
        emptyPanel = new javax.swing.JOptionPane();
        eliminarDesktopPanel = new javax.swing.JDesktopPane();
        eliminarFrame = new javax.swing.JInternalFrame();
        infoLabel = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        eliminarButton = new javax.swing.JButton();

        eliminadaDialog.setSize(new java.awt.Dimension(300, 200));

        eliminadaPanel.setMessageType(JOptionPane.INFORMATION_MESSAGE);

        javax.swing.GroupLayout eliminadaDialogLayout = new javax.swing.GroupLayout(eliminadaDialog.getContentPane());
        eliminadaDialog.getContentPane().setLayout(eliminadaDialogLayout);
        eliminadaDialogLayout.setHorizontalGroup(
            eliminadaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminadaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        eliminadaDialogLayout.setVerticalGroup(
            eliminadaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminadaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        noExisteDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        noExisteDialog.setSize(new java.awt.Dimension(300, 200));

        noExistePanel.setMessageType(JOptionPane.ERROR_MESSAGE);

        javax.swing.GroupLayout noExisteDialogLayout = new javax.swing.GroupLayout(noExisteDialog.getContentPane());
        noExisteDialog.getContentPane().setLayout(noExisteDialogLayout);
        noExisteDialogLayout.setHorizontalGroup(
            noExisteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noExistePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        noExisteDialogLayout.setVerticalGroup(
            noExisteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noExistePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        emptyDialog.setSize(new java.awt.Dimension(300, 200));

        emptyPanel.setMessageType(JOptionPane.WARNING_MESSAGE);
        emptyPanel.setMaximumSize(new java.awt.Dimension(262020202, 90645));
        emptyPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        emptyPanel.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout emptyDialogLayout = new javax.swing.GroupLayout(emptyDialog.getContentPane());
        emptyDialog.getContentPane().setLayout(emptyDialogLayout);
        emptyDialogLayout.setHorizontalGroup(
            emptyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        emptyDialogLayout.setVerticalGroup(
            emptyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emptyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        eliminarFrame.setClosable(true);
        eliminarFrame.setVisible(true);

        infoLabel.setText("Inserte el título de la película que desea eliminar:");

        eliminarButton.setText("Eliminar película");
        eliminarButton.setMaximumSize(new java.awt.Dimension(160, 24));
        eliminarButton.setMinimumSize(new java.awt.Dimension(160, 24));
        eliminarButton.setPreferredSize(new java.awt.Dimension(160, 24));
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarFrameLayout = new javax.swing.GroupLayout(eliminarFrame.getContentPane());
        eliminarFrame.getContentPane().setLayout(eliminarFrameLayout);
        eliminarFrameLayout.setHorizontalGroup(
            eliminarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarFrameLayout.createSequentialGroup()
                .addGroup(eliminarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarFrameLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(eliminarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tituloField)))
                    .addGroup(eliminarFrameLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        eliminarFrameLayout.setVerticalGroup(
            eliminarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarFrameLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        eliminarDesktopPanel.setLayer(eliminarFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout eliminarDesktopPanelLayout = new javax.swing.GroupLayout(eliminarDesktopPanel);
        eliminarDesktopPanel.setLayout(eliminarDesktopPanelLayout);
        eliminarDesktopPanelLayout.setHorizontalGroup(
            eliminarDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarFrame)
        );
        eliminarDesktopPanelLayout.setVerticalGroup(
            eliminarDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarFrame)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        emptyPanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (emptyDialog.isVisible() && e.getSource() == emptyPanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                emptyDialog.setVisible(false);
                emptyDialog.dispose();
                emptyPanel.setValue(null);
            }
        });
        
        eliminadaPanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (eliminadaDialog.isVisible() && e.getSource() == eliminadaPanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                eliminadaDialog.setVisible(false);
                eliminadaDialog.dispose();
                eliminadaPanel.setValue(null);
            }
        });
        
        noExistePanel.addPropertyChangeListener(e -> {
            String prop = e.getPropertyName();
            if (noExisteDialog.isVisible() && e.getSource() == noExistePanel && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                noExisteDialog.setVisible(false);
                noExisteDialog.dispose();
                noExistePanel.setValue(null);
            }
        });
        
        if(tituloField.getText().isEmpty()){
            emptyDialog.setLocationRelativeTo(this);
            emptyDialog.setVisible(true);
        } else{
            eliminarPelicula("datos.tsv");
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    public void setTituloVentana(String titulo){
        eliminarFrame.setTitle(titulo);
    }
    
    public void setInfoLabel(String info){
        infoLabel.setText(info);
    }
    
    public void setEliminarButton(String eliminar){
        eliminarButton.setText(eliminar);
    }
    
    public void setEmptyDialog(String mensaje, String boton, String titulo){
        emptyPanel.setMessage(mensaje);
        emptyPanel.setOptions(new Object[]{boton});
        emptyDialog.setTitle(titulo);
    }
    
    public void setEliminadaDialog(String mensaje, String boton, String titulo){
        eliminadaPanel.setMessage(mensaje);
        eliminadaPanel.setOptions(new Object[]{boton});
        eliminadaDialog.setTitle(titulo);
    }
    
    public void setnoExisteDialog(String mensaje, String boton, String titulo){
        noExistePanel.setMessage(mensaje);
        noExistePanel.setOptions(new Object[]{boton});
        noExisteDialog.setTitle(titulo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog eliminadaDialog;
    private javax.swing.JOptionPane eliminadaPanel;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JDesktopPane eliminarDesktopPanel;
    private javax.swing.JInternalFrame eliminarFrame;
    private javax.swing.JDialog emptyDialog;
    private javax.swing.JOptionPane emptyPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JDialog noExisteDialog;
    private javax.swing.JOptionPane noExistePanel;
    private javax.swing.JTextField tituloField;
    // End of variables declaration//GEN-END:variables
}
