[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning:google.*
    ignore::DeprecationWarning:pydantic.*
    ignore::DeprecationWarning:uvloop.*
    ignore::DeprecationWarning:spade.*
